In [4]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [2]:
### Load data and organize

In [3]:
ratings = pd.read_csv("../data/movielens/ml-10M100K/ratings.dat", 
                      sep='::', 
                      header=None, 
                      names = ['user_id', 
                               'movie_id', 
                               'ratings', 
                               'timestamp'
                              ]
                     )

/home/rob/anaconda3/envs/grad/lib/python3.7/site-packages/ipykernel_launcher.py:7: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  import sys


FileNotFoundError: [Errno 2] No such file or directory: '../data/movielens/ml-10M100K/ratings.dat'

In [ ]:
ratings.head()

In [11]:
movies = pd.read_csv("../data/movielens/ml-10M100K/movies.dat", 
                      sep='::', 
                      header=None, 
                      names = ['movie_id', 
                               'title', 
                               'generes'
                              ]
                     )

C:\Users\rhall\AppData\Local\Continuum\anaconda3\envs\graddesc\lib\site-packages\ipykernel_launcher.py:6: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [18]:
movies.loc[120,:]

movie_id                 122
title       Boomerang (1992)
generes       Comedy|Romance
Name: 120, dtype: object

In [13]:
rating_movies = ratings.merge(movies[['movie_id', 'title']])

In [14]:
rating_movies.head()

user_id  movie_id  ratings   timestamp             title
0        1       122      5.0   838985046  Boomerang (1992)
1      139       122      3.0   974302621  Boomerang (1992)
2      149       122      2.5  1112342322  Boomerang (1992)
3      182       122      3.0   943458784  Boomerang (1992)
4      215       122      4.5  1102493547  Boomerang (1992)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(ratings[['user_id', 'movie_id']], 
                                                    ratings['ratings'], 
                                                    test_size=0.33, 
                                                    random_state=42)

In [26]:
train = X_train.merge(y_train, left_index = True, right_index = True)

In [31]:
train = train.pivot(index = 'user_id', columns = "movie_id", values = "ratings").fillna(0).head()

In [53]:
import sys
sys.path.append("../src")
from grad_desc_algos import gd

In [55]:
factors = 5

users = np.random.uniform(low = 1, high = 5, size = (X_train.shape, factors))
movies = np.random.uniform(low = 1, high = 5, size = (X_train.shape, factors))


def embedding(users, movies, range_values = [0,5.5]):
    dot_product = users * movies
    sum_return = dot_product.sum(1)
    within_range = 1. / (1. + np.exp(-sum_return)) + (range_values[1]/range_values[0]) + range_values[0]
    return within_range

error = embedding(users, movies) - y_train
grad = np.dot(embedding(users, movies).transpose(), error) 

    



NameError: name 'X_train' is not defined

In [143]:
## Take step back and build from simple model

In [5]:
collab_filter_test = np.random.random((20,20))*5

In [6]:
collab_filter_test

array([[4.21791803e+00, 3.16337844e+00, 3.93045925e+00, 9.17643902e-01,
        1.68319697e+00, 3.97121476e+00, 3.89068029e+00, 2.59513935e+00,
        2.61586360e+00, 1.53423832e+00, 7.18398100e-01, 3.36170374e+00,
        4.02770444e+00, 3.39432549e+00, 3.56418578e+00, 2.20910662e+00,
        1.09685912e+00, 5.10928887e-01, 1.60270801e+00, 4.73603621e+00],
       [1.02884168e-01, 2.18872444e+00, 3.57034395e+00, 1.89377826e-01,
        2.94035240e+00, 3.93755694e-01, 1.05732386e+00, 4.20015406e+00,
        2.01719956e+00, 3.82956048e+00, 2.11435602e+00, 1.65251281e+00,
        3.05078503e+00, 1.71572656e+00, 1.94853225e+00, 5.16763708e-01,
        6.84772150e-02, 4.21214040e-01, 7.01279140e-01, 4.87191911e+00],
       [4.19145779e+00, 3.43864004e+00, 4.18803507e+00, 1.28469535e+00,
        2.85756152e+00, 1.18217123e+00, 1.06278347e+00, 4.61969156e+00,
        3.19972295e+00, 8.56935097e-01, 6.31536364e-01, 2.89094388e+00,
        1.48634759e+00, 4.65388914e+00, 3.40678685e+00, 3.9002

In [7]:
users = np.random.random((20, 4))

In [8]:
movies = np.random.random((20,4))

In [9]:
## Create embedding matrix for users
users

array([[0.3398253 , 0.56562425, 0.04668423, 0.26817501],
       [0.92821385, 0.9216384 , 0.03401308, 0.97368847],
       [0.18001497, 0.26236406, 0.69775174, 0.42902004],
       [0.65569343, 0.41686878, 0.11487047, 0.40495203],
       [0.19430006, 0.68413972, 0.38348336, 0.42724225],
       [0.17682207, 0.56257704, 0.68545782, 0.67974411],
       [0.44387458, 0.05698586, 0.99121793, 0.02098242],
       [0.22245526, 0.46600352, 0.26282127, 0.78842346],
       [0.63679899, 0.78497889, 0.39678319, 0.24410133],
       [0.84918574, 0.34059252, 0.82564295, 0.83324587],
       [0.953117  , 0.0978346 , 0.48549535, 0.14198005],
       [0.88689422, 0.13662138, 0.54110329, 0.08654047],
       [0.47020518, 0.77894022, 0.22966809, 0.29978828],
       [0.61471539, 0.46926102, 0.52306248, 0.84834404],
       [0.97828236, 0.48411506, 0.04355314, 0.54304267],
       [0.69328987, 0.59534315, 0.23355631, 0.42806678],
       [0.80559655, 0.83889423, 0.89037264, 0.61638893],
       [0.71080813, 0.24008889,

In [10]:
## Create embedding matrix for movies
movies

array([[0.47406439, 0.83099936, 0.43023463, 0.71794878],
       [0.42592954, 0.29472099, 0.95678581, 0.5831876 ],
       [0.94229266, 0.59988855, 0.82877566, 0.09887316],
       [0.9934714 , 0.49836027, 0.92178897, 0.82511234],
       [0.31312728, 0.00622409, 0.65242888, 0.04940913],
       [0.15667891, 0.76235452, 0.89848144, 0.86025965],
       [0.39883193, 0.53790215, 0.63996177, 0.16945314],
       [0.06751476, 0.24143622, 0.41757011, 0.28644029],
       [0.04580991, 0.22958111, 0.96550021, 0.85226908],
       [0.08710674, 0.72268759, 0.04647162, 0.10695143],
       [0.87887563, 0.70259517, 0.21240171, 0.11063293],
       [0.92259346, 0.99797741, 0.64782434, 0.48796577],
       [0.78555134, 0.36089464, 0.21913005, 0.65728864],
       [0.3229733 , 0.96689407, 0.43327176, 0.7122975 ],
       [0.44024918, 0.62901489, 0.08695015, 0.46582323],
       [0.24855033, 0.20164482, 0.8201239 , 0.20040375],
       [0.0332697 , 0.77542541, 0.33093744, 0.45924153],
       [0.64164124, 0.01892694,

In [38]:
dot = users *  movies

In [39]:
dot

array([[1.61099071e-01, 4.70033386e-01, 2.00851725e-02, 1.92535919e-01],
       [3.95353694e-01, 2.71626186e-01, 3.25432316e-02, 5.67843044e-01],
       [1.69626784e-01, 1.57389198e-01, 5.78279665e-01, 4.24185683e-02],
       [6.51412673e-01, 2.07750841e-01, 1.05886329e-01, 3.34130918e-01],
       [6.08406515e-02, 4.25814762e-03, 2.50195618e-01, 2.11096664e-02],
       [2.77042899e-02, 4.28883146e-01, 6.15871129e-01, 5.84756430e-01],
       [1.77031353e-01, 3.06528179e-02, 6.34341586e-01, 3.55553673e-03],
       [1.50190142e-02, 1.12510129e-01, 1.09746307e-01, 2.25836245e-01],
       [2.91717061e-02, 1.80216322e-01, 3.83094256e-01, 2.08040018e-01],
       [7.39698043e-02, 2.46141992e-01, 3.83689630e-02, 8.91168362e-02],
       [8.37671302e-01, 6.87381196e-02, 1.03120041e-01, 1.57076689e-02],
       [8.18242808e-01, 1.36345052e-01, 3.50539879e-01, 4.22287888e-02],
       [3.69370305e-01, 2.81115348e-01, 5.03271809e-02, 1.97047433e-01],
       [1.98536656e-01, 4.53725701e-01, 2.26628199e

In [45]:
estimated = dot.sum(1) ## Sum over rows. Don't lose track that these correspond to a matrix that is users, movies, review. 

In [46]:
sigm = 1. / (1. + np.exp(-estimated))
sigm 

array([0.69925517, 0.78029154, 0.72065526, 0.78569707, 0.58331677,
       0.83986379, 0.6996394 , 0.6137521 , 0.6900862 , 0.61006789,
       0.73599147, 0.79369712, 0.71050959, 0.81504999, 0.72947339,
       0.63869316, 0.77816952, 0.81638595, 0.71119777, 0.52513567])

In [47]:
sigm = sigm * (5.5-0) + 0

In [48]:
sigm 

array([3.84590342, 4.29160349, 3.96360391, 4.32133391, 3.20824223,
       4.61925087, 3.84801669, 3.37563653, 3.79547407, 3.35537339,
       4.0479531 , 4.36533414, 3.90780274, 4.48277496, 4.01210366,
       3.51281239, 4.27993236, 4.4901227 , 3.91158773, 2.8882462 ])

## Figure out forward from fastai

https://github.com/hiromis/notes/blob/master/Lesson4.md

https://github.com/hiromis/notes/blob/master/Lesson5.md