In [19]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

In [5]:
### Load data and organize

In [9]:
ratings = pd.read_csv("../data/movielens/ml-10M100K/ratings.dat", 
                      sep='::', 
                      header=None, 
                      names = ['user_id', 
                               'movie_id', 
                               'ratings', 
                               'timestamp'
                              ]
                     )

C:\Users\rhall\AppData\Local\Continuum\anaconda3\envs\graddesc\lib\site-packages\ipykernel_launcher.py:7: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  import sys


In [10]:
ratings.head()

user_id  movie_id  ratings  timestamp
0        1       122      5.0  838985046
1        1       185      5.0  838983525
2        1       231      5.0  838983392
3        1       292      5.0  838983421
4        1       316      5.0  838983392

In [11]:
movies = pd.read_csv("../data/movielens/ml-10M100K/movies.dat", 
                      sep='::', 
                      header=None, 
                      names = ['movie_id', 
                               'title', 
                               'generes'
                              ]
                     )

C:\Users\rhall\AppData\Local\Continuum\anaconda3\envs\graddesc\lib\site-packages\ipykernel_launcher.py:6: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [18]:
movies.loc[120,:]

movie_id                 122
title       Boomerang (1992)
generes       Comedy|Romance
Name: 120, dtype: object

In [13]:
rating_movies = ratings.merge(movies[['movie_id', 'title']])

In [14]:
rating_movies.head()

user_id  movie_id  ratings   timestamp             title
0        1       122      5.0   838985046  Boomerang (1992)
1      139       122      3.0   974302621  Boomerang (1992)
2      149       122      2.5  1112342322  Boomerang (1992)
3      182       122      3.0   943458784  Boomerang (1992)
4      215       122      4.5  1102493547  Boomerang (1992)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(ratings[['user_id', 'movie_id']], 
                                                    ratings['ratings'], 
                                                    test_size=0.33, 
                                                    random_state=42)

In [26]:
train = X_train.merge(y_train, left_index = True, right_index = True)

In [31]:
train = train.pivot(index = 'user_id', columns = "movie_id", values = "ratings").fillna(0).head()

In [143]:
## Take set back and build from simple model

In [66]:
collab_filter_test = np.random.random((20,20))*5

In [67]:
collab_filter_test

array([[1.90376268, 3.5185353 , 0.99994101, 1.68822033, 1.97363877,
        0.94620224, 3.39072611, 4.18387588, 2.49420787, 2.56909186,
        4.23849991, 2.1992343 , 0.06780794, 3.78063504, 4.591636  ,
        2.74327443, 4.89616803, 1.32484969, 2.80089762, 4.86600512],
       [4.81429702, 0.9889502 , 1.96663982, 0.85870534, 0.92397805,
        0.27360332, 0.86937641, 1.02401851, 3.3168356 , 4.79629112,
        4.61605672, 2.19251714, 4.87015308, 1.20528534, 1.04651591,
        3.9591749 , 3.05290852, 3.5180232 , 0.57555264, 3.67942368],
       [3.83415224, 0.2114449 , 1.4752934 , 1.76925399, 3.49493596,
        0.14672909, 4.31687546, 4.24510012, 0.88901995, 2.64211024,
        2.04106761, 4.02723525, 2.52221265, 4.60361842, 3.70214205,
        4.02183872, 4.71572303, 4.59233357, 3.27289986, 4.49162957],
       [3.39247882, 2.32381881, 0.99175643, 1.00774133, 4.70303392,
        3.84307357, 3.3124654 , 2.1680556 , 0.54962221, 2.56366108,
        2.96602743, 4.85916762, 2.41087065, 2

In [85]:
users = np.random.random((20, 4))

In [97]:
movies = np.random.random((20,4))

In [98]:
## Create embedding matrix for users
users

array([[0.71490893, 0.0386742 , 0.43159398, 0.75000077],
       [0.97041763, 0.6242268 , 0.22052009, 0.26554273],
       [0.436003  , 0.14071397, 0.00237638, 0.76416134],
       [0.76986155, 0.100884  , 0.64290877, 0.10145784],
       [0.01033065, 0.82079248, 0.67220292, 0.30634969],
       [0.3123129 , 0.03913871, 0.75564058, 0.2090313 ],
       [0.74513105, 0.28208941, 0.01510123, 0.10133793],
       [0.72717292, 0.64135843, 0.032535  , 0.18472399],
       [0.38045628, 0.52012098, 0.80282264, 0.13025713],
       [0.99823836, 0.13188924, 0.82439235, 0.70839849],
       [0.79541243, 0.47233485, 0.03795861, 0.13595875],
       [0.7090042 , 0.74853449, 0.60511803, 0.62094762],
       [0.10723316, 0.9161218 , 0.04677233, 0.53840304],
       [0.99679968, 0.60906835, 0.25557389, 0.99638105],
       [0.68659777, 0.86894543, 0.40081909, 0.95340391],
       [0.29505758, 0.78846051, 0.50872205, 0.74829045],
       [0.69289136, 0.35046565, 0.21488891, 0.57267575],
       [0.98937779, 0.3281344 ,

In [99]:
## Create embedding matrix for movies
movies

array([[0.84471984, 0.84785266, 0.9495017 , 0.33670565],
       [0.18629083, 0.69038785, 0.44763087, 0.03796591],
       [0.93984737, 0.46750281, 0.22737929, 0.38398631],
       [0.45551632, 0.97680693, 0.71944561, 0.26665843],
       [0.69415652, 0.80651559, 0.11056188, 0.59910671],
       [0.32169283, 0.89127001, 0.94872954, 0.69115967],
       [0.40890335, 0.73248409, 0.78400102, 0.20686665],
       [0.70107774, 0.19146982, 0.95998899, 0.52858078],
       [0.21609208, 0.33396445, 0.85057607, 0.99382001],
       [0.32719034, 0.16635093, 0.34715168, 0.1310913 ],
       [0.99250072, 0.94613644, 0.52476121, 0.17567919],
       [0.38591568, 0.63881842, 0.03465193, 0.80436747],
       [0.39388162, 0.74394661, 0.65746156, 0.4212823 ],
       [0.84660907, 0.61314929, 0.74515797, 0.50691167],
       [0.95802706, 0.84313942, 0.88954445, 0.57079632],
       [0.47206834, 0.89031783, 0.58822656, 0.05303433],
       [0.36757673, 0.80709631, 0.69152737, 0.3512766 ],
       [0.19004737, 0.60747682,

In [106]:
dot = np.dot(users, movies.T)

In [108]:
## 

dot

array([[1.29901649, 0.38155042, 1.07611113, 0.87393233, 1.02449837,
        1.19228647, 0.81417715, 1.31937314, 1.27987125, 0.48849194,
        1.104382  , 0.91883214, 0.91007953, 1.33075127, 1.52952954,
        0.66556903, 0.85591445, 0.70818502, 0.74236905, 0.44178935],
       [1.64777731, 0.72053167, 1.35597872, 1.28125155, 1.36053991,
        1.26127737, 1.08186312, 1.15191643, 0.86963991, 0.53271624,
        1.71611464, 0.99450234, 1.10347302, 1.5032376 , 1.8037298 ,
        1.15766234, 1.1062887 , 0.77746002, 1.19704037, 0.76087939],
       [0.74715892, 0.2084464 , 0.76952829, 0.5415366 , 0.87421926,
        0.79608523, 0.44129641, 0.73881678, 0.90267038, 0.26706374,
        0.70136219, 0.87289995, 0.59990728, 0.84453585, 0.97463855,
        0.373028  , 0.54390961, 0.60146723, 0.47014955, 0.37740249],
       [1.38045649, 0.50470499, 0.95585847, 0.93882117, 0.74763421,
        1.01764394, 0.91372426, 1.22986304, 0.8477263 , 0.50516051,
        1.21473579, 0.46543563, 0.84371683, 1

In [112]:
dot[1]

array([1.64777731, 0.72053167, 1.35597872, 1.28125155, 1.36053991,
       1.26127737, 1.08186312, 1.15191643, 0.86963991, 0.53271624,
       1.71611464, 0.99450234, 1.10347302, 1.5032376 , 1.8037298 ,
       1.15766234, 1.1062887 , 0.77746002, 1.19704037, 0.76087939])

In [114]:
sum(dot[10])

16.3106888504713

In [115]:
dot.sum(1) ## Sum over rows

array([18.95671007, 23.38388046, 12.64612269, 17.60233828, 21.75399151,
       14.19115759, 12.60468725, 18.28515228, 21.48817346, 27.38358987,
       16.31068885, 29.72479632, 18.71857449, 29.74405172, 31.48502752,
       25.91782431, 19.12607413, 21.25912941, 30.49584737, 18.77887015])

In [141]:
sigm = 1. / (1. + np.exp(-dot.sum(1)))
sigm 

array([0.99999999, 1.        , 0.99999678, 0.99999998, 1.        ,
       0.99999931, 0.99999664, 0.99999999, 1.        , 1.        ,
       0.99999992, 1.        , 0.99999999, 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.99999999])

In [142]:
sigm * (5.5-0)+0

array([5.49999997, 5.5       , 5.49998229, 5.49999988, 5.5       ,
       5.49999622, 5.49998154, 5.49999994, 5.5       , 5.5       ,
       5.49999955, 5.5       , 5.49999996, 5.5       , 5.5       ,
       5.5       , 5.49999997, 5.5       , 5.5       , 5.49999996])